# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05ea6c824fc6ee2dbf418f2d3d494e3ea7664e3110fd68b5a04d052d042c4aadd7e705cbac8fe19c28f53571eef84419ae06d6a8a1d26eee8852ada4f479c5cb

test:
  secret_key_base: 6df9d497e2cef5f1d4654542bb868089b4f348c696dd06757faa2ca1066d664b8e3e79adb6977b0a184d22f2877e152f7c78ca5879b50fd3b74383e15a86e5ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
